/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardWarehousesRouteImport } from './routes/_dashboard/warehouses'
import { Route as DashboardSuppliersRouteImport } from './routes/_dashboard/suppliers'
import { Route as DashboardStockRouteImport } from './routes/_dashboard/stock'
import { Route as DashboardSalesOrdersRouteImport } from './routes/_dashboard/sales-orders'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard/reports'
import { Route as DashboardPurchaseOrdersRouteImport } from './routes/_dashboard/purchase-orders'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardLocationsRouteImport } from './routes/_dashboard/locations'
import { Route as DashboardKitsRouteImport } from './routes/_dashboard/kits'
import { Route as DashboardGoodsReceiptsRouteImport } from './routes/_dashboard/goods-receipts'
import { Route as DashboardCustomersRouteImport } from './routes/_dashboard/customers'
import { Route as DashboardApprovalsRouteImport } from './routes/_dashboard/approvals'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardSettingsRouteRouteImport } from './routes/_dashboard/settings/route'
import { Route as DashboardProductsRouteRouteImport } from './routes/_dashboard/products/route'
import { Route as DashboardMobileRouteRouteImport } from './routes/_dashboard/mobile/route'
import { Route as DashboardCategoriesRouteRouteImport } from './routes/_dashboard/categories/route'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/_dashboard/products/index'
import { Route as DashboardMobileIndexRouteImport } from './routes/_dashboard/mobile/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/_dashboard/categories/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardWarehousesWarehouseIdRouteImport } from './routes/_dashboard/warehouses/$warehouseId'
import { Route as DashboardSuppliersSupplierIdRouteImport } from './routes/_dashboard/suppliers/$supplierId'
import { Route as DashboardSettingsUserManagementRouteImport } from './routes/_dashboard/settings/user-management'
import { Route as DashboardSettingsSystemRouteImport } from './routes/_dashboard/settings/system'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/_dashboard/settings/security'
import { Route as DashboardSettingsProfileRouteImport } from './routes/_dashboard/settings/profile'
import { Route as DashboardSettingsAuditRouteImport } from './routes/_dashboard/settings/audit'
import { Route as DashboardProductsNewRouteImport } from './routes/_dashboard/products/new'
import { Route as DashboardProductsProductIdRouteImport } from './routes/_dashboard/products/$productId'
import { Route as DashboardMobileTransferRouteImport } from './routes/_dashboard/mobile/transfer'
import { Route as DashboardMobileReceiveRouteImport } from './routes/_dashboard/mobile/receive'
import { Route as DashboardMobilePickRouteImport } from './routes/_dashboard/mobile/pick'
import { Route as DashboardLocationsLocationIdRouteImport } from './routes/_dashboard/locations/$locationId'
import { Route as DashboardCustomersCustomerIdRouteImport } from './routes/_dashboard/customers/$customerId'
import { Route as DashboardCategoriesNewRouteImport } from './routes/_dashboard/categories/new'
import { Route as DashboardCategoriesCategoryIdRouteImport } from './routes/_dashboard/categories/$categoryId'

const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWarehousesRoute = DashboardWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSuppliersRoute = DashboardSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStockRoute = DashboardStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSalesOrdersRoute = DashboardSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPurchaseOrdersRoute = DashboardPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLocationsRoute = DashboardLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKitsRoute = DashboardKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGoodsReceiptsRoute = DashboardGoodsReceiptsRouteImport.update({
  id: '/goods-receipts',
  path: '/goods-receipts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsRouteRoute = DashboardProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMobileRouteRoute = DashboardMobileRouteRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesRouteRoute =
  DashboardCategoriesRouteRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProductsRouteRoute,
} as any)
const DashboardMobileIndexRoute = DashboardMobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMobileRouteRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCategoriesRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWarehousesWarehouseIdRoute =
  DashboardWarehousesWarehouseIdRouteImport.update({
    id: '/$warehouseId',
    path: '/$warehouseId',
    getParentRoute: () => DashboardWarehousesRoute,
  } as any)
const DashboardSuppliersSupplierIdRoute =
  DashboardSuppliersSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => DashboardSuppliersRoute,
  } as any)
const DashboardSettingsUserManagementRoute =
  DashboardSettingsUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsSystemRoute = DashboardSettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAuditRoute = DashboardSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProductsRouteRoute,
} as any)
const DashboardProductsProductIdRoute =
  DashboardProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => DashboardProductsRouteRoute,
  } as any)
const DashboardMobileTransferRoute = DashboardMobileTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => DashboardMobileRouteRoute,
} as any)
const DashboardMobileReceiveRoute = DashboardMobileReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => DashboardMobileRouteRoute,
} as any)
const DashboardMobilePickRoute = DashboardMobilePickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => DashboardMobileRouteRoute,
} as any)
const DashboardLocationsLocationIdRoute =
  DashboardLocationsLocationIdRouteImport.update({
    id: '/$locationId',
    path: '/$locationId',
    getParentRoute: () => DashboardLocationsRoute,
  } as any)
const DashboardCustomersCustomerIdRoute =
  DashboardCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => DashboardCustomersRoute,
  } as any)
const DashboardCategoriesNewRoute = DashboardCategoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardCategoriesRouteRoute,
} as any)
const DashboardCategoriesCategoryIdRoute =
  DashboardCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => DashboardCategoriesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/banned': typeof BannedRoute
  '/categories': typeof DashboardCategoriesRouteRouteWithChildren
  '/mobile': typeof DashboardMobileRouteRouteWithChildren
  '/products': typeof DashboardProductsRouteRouteWithChildren
  '/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/approvals': typeof DashboardApprovalsRoute
  '/customers': typeof DashboardCustomersRouteWithChildren
  '/goods-receipts': typeof DashboardGoodsReceiptsRoute
  '/kits': typeof DashboardKitsRoute
  '/locations': typeof DashboardLocationsRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/purchase-orders': typeof DashboardPurchaseOrdersRoute
  '/reports': typeof DashboardReportsRoute
  '/sales-orders': typeof DashboardSalesOrdersRoute
  '/stock': typeof DashboardStockRoute
  '/suppliers': typeof DashboardSuppliersRouteWithChildren
  '/warehouses': typeof DashboardWarehousesRouteWithChildren
  '/categories/$categoryId': typeof DashboardCategoriesCategoryIdRoute
  '/categories/new': typeof DashboardCategoriesNewRoute
  '/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/locations/$locationId': typeof DashboardLocationsLocationIdRoute
  '/mobile/pick': typeof DashboardMobilePickRoute
  '/mobile/receive': typeof DashboardMobileReceiveRoute
  '/mobile/transfer': typeof DashboardMobileTransferRoute
  '/products/$productId': typeof DashboardProductsProductIdRoute
  '/products/new': typeof DashboardProductsNewRoute
  '/settings/audit': typeof DashboardSettingsAuditRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/settings/security': typeof DashboardSettingsSecurityRoute
  '/settings/system': typeof DashboardSettingsSystemRoute
  '/settings/user-management': typeof DashboardSettingsUserManagementRoute
  '/suppliers/$supplierId': typeof DashboardSuppliersSupplierIdRoute
  '/warehouses/$warehouseId': typeof DashboardWarehousesWarehouseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/categories/': typeof DashboardCategoriesIndexRoute
  '/mobile/': typeof DashboardMobileIndexRoute
  '/products/': typeof DashboardProductsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/banned': typeof BannedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/approvals': typeof DashboardApprovalsRoute
  '/customers': typeof DashboardCustomersRouteWithChildren
  '/goods-receipts': typeof DashboardGoodsReceiptsRoute
  '/kits': typeof DashboardKitsRoute
  '/locations': typeof DashboardLocationsRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/purchase-orders': typeof DashboardPurchaseOrdersRoute
  '/reports': typeof DashboardReportsRoute
  '/sales-orders': typeof DashboardSalesOrdersRoute
  '/stock': typeof DashboardStockRoute
  '/suppliers': typeof DashboardSuppliersRouteWithChildren
  '/warehouses': typeof DashboardWarehousesRouteWithChildren
  '/categories/$categoryId': typeof DashboardCategoriesCategoryIdRoute
  '/categories/new': typeof DashboardCategoriesNewRoute
  '/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/locations/$locationId': typeof DashboardLocationsLocationIdRoute
  '/mobile/pick': typeof DashboardMobilePickRoute
  '/mobile/receive': typeof DashboardMobileReceiveRoute
  '/mobile/transfer': typeof DashboardMobileTransferRoute
  '/products/$productId': typeof DashboardProductsProductIdRoute
  '/products/new': typeof DashboardProductsNewRoute
  '/settings/audit': typeof DashboardSettingsAuditRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/settings/security': typeof DashboardSettingsSecurityRoute
  '/settings/system': typeof DashboardSettingsSystemRoute
  '/settings/user-management': typeof DashboardSettingsUserManagementRoute
  '/suppliers/$supplierId': typeof DashboardSuppliersSupplierIdRoute
  '/warehouses/$warehouseId': typeof DashboardWarehousesWarehouseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/categories': typeof DashboardCategoriesIndexRoute
  '/mobile': typeof DashboardMobileIndexRoute
  '/products': typeof DashboardProductsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/banned': typeof BannedRoute
  '/_dashboard/categories': typeof DashboardCategoriesRouteRouteWithChildren
  '/_dashboard/mobile': typeof DashboardMobileRouteRouteWithChildren
  '/_dashboard/products': typeof DashboardProductsRouteRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_dashboard/approvals': typeof DashboardApprovalsRoute
  '/_dashboard/customers': typeof DashboardCustomersRouteWithChildren
  '/_dashboard/goods-receipts': typeof DashboardGoodsReceiptsRoute
  '/_dashboard/kits': typeof DashboardKitsRoute
  '/_dashboard/locations': typeof DashboardLocationsRouteWithChildren
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/purchase-orders': typeof DashboardPurchaseOrdersRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/sales-orders': typeof DashboardSalesOrdersRoute
  '/_dashboard/stock': typeof DashboardStockRoute
  '/_dashboard/suppliers': typeof DashboardSuppliersRouteWithChildren
  '/_dashboard/warehouses': typeof DashboardWarehousesRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/categories/$categoryId': typeof DashboardCategoriesCategoryIdRoute
  '/_dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/_dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/_dashboard/locations/$locationId': typeof DashboardLocationsLocationIdRoute
  '/_dashboard/mobile/pick': typeof DashboardMobilePickRoute
  '/_dashboard/mobile/receive': typeof DashboardMobileReceiveRoute
  '/_dashboard/mobile/transfer': typeof DashboardMobileTransferRoute
  '/_dashboard/products/$productId': typeof DashboardProductsProductIdRoute
  '/_dashboard/products/new': typeof DashboardProductsNewRoute
  '/_dashboard/settings/audit': typeof DashboardSettingsAuditRoute
  '/_dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/_dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/_dashboard/settings/system': typeof DashboardSettingsSystemRoute
  '/_dashboard/settings/user-management': typeof DashboardSettingsUserManagementRoute
  '/_dashboard/suppliers/$supplierId': typeof DashboardSuppliersSupplierIdRoute
  '/_dashboard/warehouses/$warehouseId': typeof DashboardWarehousesWarehouseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/_dashboard/mobile/': typeof DashboardMobileIndexRoute
  '/_dashboard/products/': typeof DashboardProductsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banned'
    | '/categories'
    | '/mobile'
    | '/products'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/approvals'
    | '/customers'
    | '/goods-receipts'
    | '/kits'
    | '/locations'
    | '/profile'
    | '/purchase-orders'
    | '/reports'
    | '/sales-orders'
    | '/stock'
    | '/suppliers'
    | '/warehouses'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/customers/$customerId'
    | '/locations/$locationId'
    | '/mobile/pick'
    | '/mobile/receive'
    | '/mobile/transfer'
    | '/products/$productId'
    | '/products/new'
    | '/settings/audit'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/system'
    | '/settings/user-management'
    | '/suppliers/$supplierId'
    | '/warehouses/$warehouseId'
    | '/api/auth/$'
    | '/categories/'
    | '/mobile/'
    | '/products/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banned'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/approvals'
    | '/customers'
    | '/goods-receipts'
    | '/kits'
    | '/locations'
    | '/profile'
    | '/purchase-orders'
    | '/reports'
    | '/sales-orders'
    | '/stock'
    | '/suppliers'
    | '/warehouses'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/customers/$customerId'
    | '/locations/$locationId'
    | '/mobile/pick'
    | '/mobile/receive'
    | '/mobile/transfer'
    | '/products/$productId'
    | '/products/new'
    | '/settings/audit'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/system'
    | '/settings/user-management'
    | '/suppliers/$supplierId'
    | '/warehouses/$warehouseId'
    | '/api/auth/$'
    | '/categories'
    | '/mobile'
    | '/products'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/banned'
    | '/_dashboard/categories'
    | '/_dashboard/mobile'
    | '/_dashboard/products'
    | '/_dashboard/settings'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_dashboard/approvals'
    | '/_dashboard/customers'
    | '/_dashboard/goods-receipts'
    | '/_dashboard/kits'
    | '/_dashboard/locations'
    | '/_dashboard/profile'
    | '/_dashboard/purchase-orders'
    | '/_dashboard/reports'
    | '/_dashboard/sales-orders'
    | '/_dashboard/stock'
    | '/_dashboard/suppliers'
    | '/_dashboard/warehouses'
    | '/_dashboard/'
    | '/_dashboard/categories/$categoryId'
    | '/_dashboard/categories/new'
    | '/_dashboard/customers/$customerId'
    | '/_dashboard/locations/$locationId'
    | '/_dashboard/mobile/pick'
    | '/_dashboard/mobile/receive'
    | '/_dashboard/mobile/transfer'
    | '/_dashboard/products/$productId'
    | '/_dashboard/products/new'
    | '/_dashboard/settings/audit'
    | '/_dashboard/settings/profile'
    | '/_dashboard/settings/security'
    | '/_dashboard/settings/system'
    | '/_dashboard/settings/user-management'
    | '/_dashboard/suppliers/$supplierId'
    | '/_dashboard/warehouses/$warehouseId'
    | '/api/auth/$'
    | '/_dashboard/categories/'
    | '/_dashboard/mobile/'
    | '/_dashboard/products/'
    | '/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  BannedRoute: typeof BannedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/warehouses': {
      id: '/_dashboard/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof DashboardWarehousesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/suppliers': {
      id: '/_dashboard/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof DashboardSuppliersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/stock': {
      id: '/_dashboard/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof DashboardStockRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/sales-orders': {
      id: '/_dashboard/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof DashboardSalesOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/purchase-orders': {
      id: '/_dashboard/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof DashboardPurchaseOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/locations': {
      id: '/_dashboard/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof DashboardLocationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/kits': {
      id: '/_dashboard/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof DashboardKitsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/goods-receipts': {
      id: '/_dashboard/goods-receipts'
      path: '/goods-receipts'
      fullPath: '/goods-receipts'
      preLoaderRoute: typeof DashboardGoodsReceiptsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/customers': {
      id: '/_dashboard/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/approvals': {
      id: '/_dashboard/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products': {
      id: '/_dashboard/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashboardProductsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/mobile': {
      id: '/_dashboard/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof DashboardMobileRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/categories': {
      id: '/_dashboard/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/products/': {
      id: '/_dashboard/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardProductsRouteRoute
    }
    '/_dashboard/mobile/': {
      id: '/_dashboard/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof DashboardMobileIndexRouteImport
      parentRoute: typeof DashboardMobileRouteRoute
    }
    '/_dashboard/categories/': {
      id: '/_dashboard/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardCategoriesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/warehouses/$warehouseId': {
      id: '/_dashboard/warehouses/$warehouseId'
      path: '/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof DashboardWarehousesWarehouseIdRouteImport
      parentRoute: typeof DashboardWarehousesRoute
    }
    '/_dashboard/suppliers/$supplierId': {
      id: '/_dashboard/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof DashboardSuppliersSupplierIdRouteImport
      parentRoute: typeof DashboardSuppliersRoute
    }
    '/_dashboard/settings/user-management': {
      id: '/_dashboard/settings/user-management'
      path: '/user-management'
      fullPath: '/settings/user-management'
      preLoaderRoute: typeof DashboardSettingsUserManagementRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/system': {
      id: '/_dashboard/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof DashboardSettingsSystemRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/security': {
      id: '/_dashboard/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/profile': {
      id: '/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/audit': {
      id: '/_dashboard/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof DashboardSettingsAuditRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/products/new': {
      id: '/_dashboard/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardProductsRouteRoute
    }
    '/_dashboard/products/$productId': {
      id: '/_dashboard/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof DashboardProductsProductIdRouteImport
      parentRoute: typeof DashboardProductsRouteRoute
    }
    '/_dashboard/mobile/transfer': {
      id: '/_dashboard/mobile/transfer'
      path: '/transfer'
      fullPath: '/mobile/transfer'
      preLoaderRoute: typeof DashboardMobileTransferRouteImport
      parentRoute: typeof DashboardMobileRouteRoute
    }
    '/_dashboard/mobile/receive': {
      id: '/_dashboard/mobile/receive'
      path: '/receive'
      fullPath: '/mobile/receive'
      preLoaderRoute: typeof DashboardMobileReceiveRouteImport
      parentRoute: typeof DashboardMobileRouteRoute
    }
    '/_dashboard/mobile/pick': {
      id: '/_dashboard/mobile/pick'
      path: '/pick'
      fullPath: '/mobile/pick'
      preLoaderRoute: typeof DashboardMobilePickRouteImport
      parentRoute: typeof DashboardMobileRouteRoute
    }
    '/_dashboard/locations/$locationId': {
      id: '/_dashboard/locations/$locationId'
      path: '/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof DashboardLocationsLocationIdRouteImport
      parentRoute: typeof DashboardLocationsRoute
    }
    '/_dashboard/customers/$customerId': {
      id: '/_dashboard/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof DashboardCustomersCustomerIdRouteImport
      parentRoute: typeof DashboardCustomersRoute
    }
    '/_dashboard/categories/new': {
      id: '/_dashboard/categories/new'
      path: '/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof DashboardCategoriesNewRouteImport
      parentRoute: typeof DashboardCategoriesRouteRoute
    }
    '/_dashboard/categories/$categoryId': {
      id: '/_dashboard/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof DashboardCategoriesCategoryIdRouteImport
      parentRoute: typeof DashboardCategoriesRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardCategoriesRouteRouteChildren {
  DashboardCategoriesCategoryIdRoute: typeof DashboardCategoriesCategoryIdRoute
  DashboardCategoriesNewRoute: typeof DashboardCategoriesNewRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
}

const DashboardCategoriesRouteRouteChildren: DashboardCategoriesRouteRouteChildren =
  {
    DashboardCategoriesCategoryIdRoute: DashboardCategoriesCategoryIdRoute,
    DashboardCategoriesNewRoute: DashboardCategoriesNewRoute,
    DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  }

const DashboardCategoriesRouteRouteWithChildren =
  DashboardCategoriesRouteRoute._addFileChildren(
    DashboardCategoriesRouteRouteChildren,
  )

interface DashboardMobileRouteRouteChildren {
  DashboardMobilePickRoute: typeof DashboardMobilePickRoute
  DashboardMobileReceiveRoute: typeof DashboardMobileReceiveRoute
  DashboardMobileTransferRoute: typeof DashboardMobileTransferRoute
  DashboardMobileIndexRoute: typeof DashboardMobileIndexRoute
}

const DashboardMobileRouteRouteChildren: DashboardMobileRouteRouteChildren = {
  DashboardMobilePickRoute: DashboardMobilePickRoute,
  DashboardMobileReceiveRoute: DashboardMobileReceiveRoute,
  DashboardMobileTransferRoute: DashboardMobileTransferRoute,
  DashboardMobileIndexRoute: DashboardMobileIndexRoute,
}

const DashboardMobileRouteRouteWithChildren =
  DashboardMobileRouteRoute._addFileChildren(DashboardMobileRouteRouteChildren)

interface DashboardProductsRouteRouteChildren {
  DashboardProductsProductIdRoute: typeof DashboardProductsProductIdRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardProductsRouteRouteChildren: DashboardProductsRouteRouteChildren =
  {
    DashboardProductsProductIdRoute: DashboardProductsProductIdRoute,
    DashboardProductsNewRoute: DashboardProductsNewRoute,
    DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  }

const DashboardProductsRouteRouteWithChildren =
  DashboardProductsRouteRoute._addFileChildren(
    DashboardProductsRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAuditRoute: typeof DashboardSettingsAuditRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsSystemRoute: typeof DashboardSettingsSystemRoute
  DashboardSettingsUserManagementRoute: typeof DashboardSettingsUserManagementRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAuditRoute: DashboardSettingsAuditRoute,
    DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
    DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
    DashboardSettingsSystemRoute: DashboardSettingsSystemRoute,
    DashboardSettingsUserManagementRoute: DashboardSettingsUserManagementRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardCustomersRouteChildren {
  DashboardCustomersCustomerIdRoute: typeof DashboardCustomersCustomerIdRoute
}

const DashboardCustomersRouteChildren: DashboardCustomersRouteChildren = {
  DashboardCustomersCustomerIdRoute: DashboardCustomersCustomerIdRoute,
}

const DashboardCustomersRouteWithChildren =
  DashboardCustomersRoute._addFileChildren(DashboardCustomersRouteChildren)

interface DashboardLocationsRouteChildren {
  DashboardLocationsLocationIdRoute: typeof DashboardLocationsLocationIdRoute
}

const DashboardLocationsRouteChildren: DashboardLocationsRouteChildren = {
  DashboardLocationsLocationIdRoute: DashboardLocationsLocationIdRoute,
}

const DashboardLocationsRouteWithChildren =
  DashboardLocationsRoute._addFileChildren(DashboardLocationsRouteChildren)

interface DashboardSuppliersRouteChildren {
  DashboardSuppliersSupplierIdRoute: typeof DashboardSuppliersSupplierIdRoute
}

const DashboardSuppliersRouteChildren: DashboardSuppliersRouteChildren = {
  DashboardSuppliersSupplierIdRoute: DashboardSuppliersSupplierIdRoute,
}

const DashboardSuppliersRouteWithChildren =
  DashboardSuppliersRoute._addFileChildren(DashboardSuppliersRouteChildren)

interface DashboardWarehousesRouteChildren {
  DashboardWarehousesWarehouseIdRoute: typeof DashboardWarehousesWarehouseIdRoute
}

const DashboardWarehousesRouteChildren: DashboardWarehousesRouteChildren = {
  DashboardWarehousesWarehouseIdRoute: DashboardWarehousesWarehouseIdRoute,
}

const DashboardWarehousesRouteWithChildren =
  DashboardWarehousesRoute._addFileChildren(DashboardWarehousesRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardCategoriesRouteRoute: typeof DashboardCategoriesRouteRouteWithChildren
  DashboardMobileRouteRoute: typeof DashboardMobileRouteRouteWithChildren
  DashboardProductsRouteRoute: typeof DashboardProductsRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRouteWithChildren
  DashboardGoodsReceiptsRoute: typeof DashboardGoodsReceiptsRoute
  DashboardKitsRoute: typeof DashboardKitsRoute
  DashboardLocationsRoute: typeof DashboardLocationsRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardPurchaseOrdersRoute: typeof DashboardPurchaseOrdersRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSalesOrdersRoute: typeof DashboardSalesOrdersRoute
  DashboardStockRoute: typeof DashboardStockRoute
  DashboardSuppliersRoute: typeof DashboardSuppliersRouteWithChildren
  DashboardWarehousesRoute: typeof DashboardWarehousesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCategoriesRouteRoute: DashboardCategoriesRouteRouteWithChildren,
  DashboardMobileRouteRoute: DashboardMobileRouteRouteWithChildren,
  DashboardProductsRouteRoute: DashboardProductsRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardCustomersRoute: DashboardCustomersRouteWithChildren,
  DashboardGoodsReceiptsRoute: DashboardGoodsReceiptsRoute,
  DashboardKitsRoute: DashboardKitsRoute,
  DashboardLocationsRoute: DashboardLocationsRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardPurchaseOrdersRoute: DashboardPurchaseOrdersRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSalesOrdersRoute: DashboardSalesOrdersRoute,
  DashboardStockRoute: DashboardStockRoute,
  DashboardSuppliersRoute: DashboardSuppliersRouteWithChildren,
  DashboardWarehousesRoute: DashboardWarehousesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  BannedRoute: BannedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
